Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1-cilium"
    vm1.vm.network "private_network", ip: "192.168.56.10"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-vm1"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2-cilium"
    vm2.vm.network "private_network", ip: "192.168.56.11"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-vm2"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end